<?php declare(strict_types=1);

const CARD_METADATA = [
    'attr_str_1' => [
        'source_name' => clienttranslate('Card_2.png'),
        'asset_name' => clienttranslate('attr_str_1'),
        'title' => clienttranslate('Strength +1'),
    ],
    'attr_dex_1' => [
        'source_name' => clienttranslate('Card_3.png'),
        'asset_name' => clienttranslate('attr_dex_1'),
        'title' => clienttranslate('Dexterity +1'),
    ],
    'attr_con_1' => [
        'source_name' => clienttranslate('Card_4.png'),
        'asset_name' => clienttranslate('attr_con_1'),
        'title' => clienttranslate('Constitution +1'),
    ],
    'attr_wis_1' => [
        'source_name' => clienttranslate('Card_5.png'),
        'asset_name' => clienttranslate('attr_wis_1'),
        'title' => clienttranslate('Wisdom +1'),
    ],
    'attr_int_1' => [
        'source_name' => clienttranslate('Card_6.png'),
        'asset_name' => clienttranslate('attr_int_1'),
        'title' => clienttranslate('Intelligence +1'),
    ],
    'attr_cha_1' => [
        'source_name' => clienttranslate('Card_7.png'),
        'asset_name' => clienttranslate('attr_cha_1'),
        'title' => clienttranslate('Charisma +1'),
    ],
    'attr_str_2' => [
        'source_name' => clienttranslate('Card_8.png'),
        'asset_name' => clienttranslate('attr_str_2'),
        'title' => clienttranslate('Strength +2'),
    ],
    'attr_dex_2' => [
        'source_name' => clienttranslate('Card_9.png'),
        'asset_name' => clienttranslate('attr_dex_2'),
        'title' => clienttranslate('Dexterity +2'),
    ],
    'attr_con_2' => [
        'source_name' => clienttranslate('Card_10.png'),
        'asset_name' => clienttranslate('attr_con_2'),
        'title' => clienttranslate('Constitution +2'),
    ],
    'attr_wis_2' => [
        'source_name' => clienttranslate('Card_11.png'),
        'asset_name' => clienttranslate('attr_wis_2'),
        'title' => clienttranslate('Wisdom +2'),
    ],
    'attr_int_2' => [
        'source_name' => clienttranslate('Card_12.png'),
        'asset_name' => clienttranslate('attr_int_2'),
        'title' => clienttranslate('Intelligence +2'),
    ],
    'attr_cha_2' => [
        'source_name' => clienttranslate('Card_13.png'),
        'asset_name' => clienttranslate('attr_cha_2'),
        'title' => clienttranslate('Charisma +2'),
    ],
    'item_1' => [
        'source_name' => clienttranslate('Card_27.png'),
        'item_no' => 1,
        'title' => clienttranslate('Silver Sword'),
        'points' => 8,
        'requires' => ['str' => 5],
        'asset_name' => clienttranslate('item_1'),
    ],
    'item_2' => [
        'source_name' => clienttranslate('Card_28.png'),
        'item_no' => 2,
        'title' => clienttranslate('Compact Crossbow'),
        'points' => 8,
        'requires' => ['dex' => 5],
        'asset_name' => clienttranslate('item_2'),
    ],
    'item_3' => [
        'source_name' => clienttranslate('Card_29.png'),
        'item_no' => 3,
        'title' => clienttranslate('Poison Antidote'),
        'points' => 8,
        'requires' => ['con' => 5],
        'asset_name' => clienttranslate('item_3'),
    ],
    'item_4' => [
        'source_name' => clienttranslate('Card_30.png'),
        'item_no' => 4,
        'title' => clienttranslate('Binding Rope'),
        'points' => 8,
        'requires' => ['int' => 5],
        'asset_name' => clienttranslate('item_4'),
    ],
    'item_5' => [
        'source_name' => clienttranslate('Card_31.png'),
        'item_no' => 5,
        'title' => clienttranslate('Phantom Lantern'),
        'points' => 8,
        'requires' => ['wis' => 5],
        'asset_name' => clienttranslate('item_5'),
    ],
    'item_6' => [
        'source_name' => clienttranslate('Card_32.png'),
        'item_no' => 6,
        'title' => clienttranslate('Loaded Dice'),
        'points' => 8,
        'requires' => ['cha' => 5],
        'asset_name' => clienttranslate('item_6'),
    ],
    'item_7' => [
        'source_name' => clienttranslate('Card_33.png'),
        'item_no' => 7,
        'title' => clienttranslate('Handy Cannon'),
        'points' => 6,
        'requires' => ['str' => 3, 'dex' => 3],
        'asset_name' => clienttranslate('item_7'),
    ],
    'item_8' => [
        'source_name' => clienttranslate('Card_34.png'),
        'item_no' => 8,
        'title' => clienttranslate('Reflective Shield'),
        'points' => 6,
        'requires' => ['wis' => 3, 'int' => 3],
        'asset_name' => clienttranslate('item_8'),
    ],
    'item_9' => [
        'source_name' => clienttranslate('Card_35.png'),
        'item_no' => 9,
        'title' => clienttranslate('Awakened Artifact'),
        'points' => 6,
        'requires' => ['con' => 3, 'cha' => 3],
        'asset_name' => clienttranslate('item_9'),
    ],
    'item_10' => [
        'source_name' => clienttranslate('Card_36.png'),
        'item_no' => 10,
        'title' => clienttranslate('Wooden Stake'),
        'points' => 4,
        'requires' => ['str' => 2, 'cha' => 2],
        'asset_name' => clienttranslate('item_10'),
    ],
    'item_11' => [
        'source_name' => clienttranslate('Card_37.png'),
        'item_no' => 11,
        'title' => clienttranslate('Glacial Spear'),
        'points' => 4,
        'requires' => ['str' => 2, 'int' => 2],
        'asset_name' => clienttranslate('item_11'),
    ],
    'item_12' => [
        'source_name' => clienttranslate('Card_38.png'),
        'item_no' => 12,
        'title' => clienttranslate('Sea Trident'),
        'points' => 4,
        'requires' => ['str' => 2, 'wis' => 2],
        'asset_name' => clienttranslate('item_12'),
    ],
    'item_13' => [
        'source_name' => clienttranslate('Card_39.png'),
        'item_no' => 13,
        'title' => clienttranslate('Iron Horseshoes'),
        'points' => 4,
        'requires' => ['str' => 2, 'int' => 2],
        'asset_name' => clienttranslate('item_13'),
    ],
    'item_14' => [
        'source_name' => clienttranslate('Card_40.png'),
        'item_no' => 14,
        'title' => clienttranslate('Holy Water'),
        'points' => 4,
        'requires' => ['dex' => 2, 'con' => 2],
        'asset_name' => clienttranslate('item_14'),
    ],
    'item_15' => [
        'source_name' => clienttranslate('Card_41.png'),
        'item_no' => 15,
        'title' => clienttranslate('Explosive Trap'),
        'points' => 4,
        'requires' => ['dex' => 2, 'int' => 2],
        'asset_name' => clienttranslate('item_15'),
    ],
    'item_16' => [
        'source_name' => clienttranslate('Card_42.png'),
        'item_no' => 16,
        'title' => clienttranslate('Woven Net'),
        'points' => 4,
        'requires' => ['dex' => 2, 'wis' => 2],
        'asset_name' => clienttranslate('item_16'),
    ],
    'item_17' => [
        'source_name' => clienttranslate('Card_43.png'),
        'item_no' => 17,
        'title' => clienttranslate('Hypnotic Flute'),
        'points' => 4,
        'requires' => ['dex' => 2, 'cha' => 2],
        'asset_name' => clienttranslate('item_17'),
    ],
    'item_18' => [
        'source_name' => clienttranslate('Card_44.png'),
        'item_no' => 18,
        'title' => clienttranslate('Crystal Goggles'),
        'points' => 4,
        'requires' => ['con' => 2, 'int' => 2],
        'asset_name' => clienttranslate('item_18'),
    ],
    'item_19' => [
        'source_name' => clienttranslate('Card_45.png'),
        'item_no' => 19,
        'title' => clienttranslate('Burning Torch'),
        'points' => 4,
        'requires' => ['con' => 2, 'wis' => 2],
        'asset_name' => clienttranslate('item_19'),
    ],
    'item_20' => [
        'source_name' => clienttranslate('Card_46.png'),
        'item_no' => 20,
        'title' => clienttranslate('Music Box'),
        'points' => 4,
        'requires' => ['con' => 2, 'int' => 2],
        'asset_name' => clienttranslate('item_20'),
    ],
    'item_21' => [
        'source_name' => clienttranslate('Card_47.png'),
        'item_no' => 21,
        'title' => clienttranslate('Cheese Wheel'),
        'points' => 4,
        'requires' => ['wis' => 2, 'cha' => 2],
        'asset_name' => clienttranslate('item_21'),
    ],
    'armor_mage_head' => [
        'source_name' => clienttranslate('Card_48.png'),
        'card_group' => clienttranslate('armor'),
        'armor_set' => clienttranslate('mage'),
        'armor_slot' => clienttranslate('head'),
        'asset_name' => clienttranslate('armor_mage_head'),
        'title' => clienttranslate('Armor: mage head'),
    ],
    'armor_mage_chest' => [
        'source_name' => clienttranslate('Card_49.png'),
        'card_group' => clienttranslate('armor'),
        'armor_set' => clienttranslate('mage'),
        'armor_slot' => clienttranslate('chest'),
        'asset_name' => clienttranslate('armor_mage_chest'),
        'title' => clienttranslate('Armor: mage chest'),
    ],
    'armor_mage_hands' => [
        'source_name' => clienttranslate('Card_50.png'),
        'card_group' => clienttranslate('armor'),
        'armor_set' => clienttranslate('mage'),
        'armor_slot' => clienttranslate('hands'),
        'asset_name' => clienttranslate('armor_mage_hands'),
        'title' => clienttranslate('Armor: mage hands'),
    ],
    'armor_mage_feet' => [
        'source_name' => clienttranslate('Card_51.png'),
        'card_group' => clienttranslate('armor'),
        'armor_set' => clienttranslate('mage'),
        'armor_slot' => clienttranslate('feet'),
        'asset_name' => clienttranslate('armor_mage_feet'),
        'title' => clienttranslate('Armor: mage feet'),
    ],
    'armor_plate_head' => [
        'source_name' => clienttranslate('Card_52.png'),
        'card_group' => clienttranslate('armor'),
        'armor_set' => clienttranslate('plate'),
        'armor_slot' => clienttranslate('head'),
        'asset_name' => clienttranslate('armor_plate_head'),
        'title' => clienttranslate('Armor: plate head'),
    ],
    'armor_plate_chest' => [
        'source_name' => clienttranslate('Card_53.png'),
        'card_group' => clienttranslate('armor'),
        'armor_set' => clienttranslate('plate'),
        'armor_slot' => clienttranslate('chest'),
        'asset_name' => clienttranslate('armor_plate_chest'),
        'title' => clienttranslate('Armor: plate chest'),
    ],
    'armor_plate_hands' => [
        'source_name' => clienttranslate('Card_54.png'),
        'card_group' => clienttranslate('armor'),
        'armor_set' => clienttranslate('plate'),
        'armor_slot' => clienttranslate('hands'),
        'asset_name' => clienttranslate('armor_plate_hands'),
        'title' => clienttranslate('Armor: plate hands'),
    ],
    'armor_plate_feet' => [
        'source_name' => clienttranslate('Card_55.png'),
        'card_group' => clienttranslate('armor'),
        'armor_set' => clienttranslate('plate'),
        'armor_slot' => clienttranslate('feet'),
        'asset_name' => clienttranslate('armor_plate_feet'),
        'title' => clienttranslate('Armor: plate feet'),
    ],
    'armor_leather_head' => [
        'source_name' => clienttranslate('Card_56.png'),
        'card_group' => clienttranslate('armor'),
        'armor_set' => clienttranslate('leather'),
        'armor_slot' => clienttranslate('head'),
        'asset_name' => clienttranslate('armor_leather_head'),
        'title' => clienttranslate('Armor: leather head'),
    ],
    'armor_leather_chest' => [
        'source_name' => clienttranslate('Card_57.png'),
        'card_group' => clienttranslate('armor'),
        'armor_set' => clienttranslate('leather'),
        'armor_slot' => clienttranslate('chest'),
        'asset_name' => clienttranslate('armor_leather_chest'),
        'title' => clienttranslate('Armor: leather chest'),
    ],
    'armor_leather_hands' => [
        'source_name' => clienttranslate('Card_58.png'),
        'card_group' => clienttranslate('armor'),
        'armor_set' => clienttranslate('leather'),
        'armor_slot' => clienttranslate('hands'),
        'asset_name' => clienttranslate('armor_leather_hands'),
        'title' => clienttranslate('Armor: leather hands'),
    ],
    'armor_leather_feet' => [
        'source_name' => clienttranslate('Card_59.png'),
        'card_group' => clienttranslate('armor'),
        'armor_set' => clienttranslate('leather'),
        'armor_slot' => clienttranslate('feet'),
        'asset_name' => clienttranslate('armor_leather_feet'),
        'title' => clienttranslate('Armor: leather feet'),
    ],
    'armor_obsidian_head' => [
        'source_name' => clienttranslate('Card_60.png'),
        'card_group' => clienttranslate('armor'),
        'armor_set' => clienttranslate('obsidian'),
        'armor_slot' => clienttranslate('head'),
        'asset_name' => clienttranslate('armor_obsidian_head'),
        'title' => clienttranslate('Armor: obsidian head'),
    ],
    'armor_obsidian_chest' => [
        'source_name' => clienttranslate('Card_61.png'),
        'card_group' => clienttranslate('armor'),
        'armor_set' => clienttranslate('obsidian'),
        'armor_slot' => clienttranslate('chest'),
        'asset_name' => clienttranslate('armor_obsidian_chest'),
        'title' => clienttranslate('Armor: obsidian chest'),
    ],
    'armor_obsidian_hands' => [
        'source_name' => clienttranslate('Card_62.png'),
        'card_group' => clienttranslate('armor'),
        'armor_set' => clienttranslate('obsidian'),
        'armor_slot' => clienttranslate('hands'),
        'asset_name' => clienttranslate('armor_obsidian_hands'),
        'title' => clienttranslate('Armor: obsidian hands'),
    ],
    'armor_obsidian_feet' => [
        'source_name' => clienttranslate('Card_63.png'),
        'card_group' => clienttranslate('armor'),
        'armor_set' => clienttranslate('obsidian'),
        'armor_slot' => clienttranslate('feet'),
        'asset_name' => clienttranslate('armor_obsidian_feet'),
        'title' => clienttranslate('Armor: obsidian feet'),
    ],
    'armor_scale_head' => [
        'source_name' => clienttranslate('Card_64.png'),
        'card_group' => clienttranslate('armor'),
        'armor_set' => clienttranslate('scale'),
        'armor_slot' => clienttranslate('head'),
        'asset_name' => clienttranslate('armor_scale_head'),
        'title' => clienttranslate('Armor: scale head'),
    ],
    'armor_scale_chest' => [
        'source_name' => clienttranslate('Card_65.png'),
        'card_group' => clienttranslate('armor'),
        'armor_set' => clienttranslate('scale'),
        'armor_slot' => clienttranslate('chest'),
        'asset_name' => clienttranslate('armor_scale_chest'),
        'title' => clienttranslate('Armor: scale chest'),
    ],
    'armor_scale_hands' => [
        'source_name' => clienttranslate('Card_66.png'),
        'card_group' => clienttranslate('armor'),
        'armor_set' => clienttranslate('scale'),
        'armor_slot' => clienttranslate('hands'),
        'asset_name' => clienttranslate('armor_scale_hands'),
        'title' => clienttranslate('Armor: scale hands'),
    ],
    'armor_scale_feet' => [
        'source_name' => clienttranslate('Card_67.png'),
        'card_group' => clienttranslate('armor'),
        'armor_set' => clienttranslate('scale'),
        'armor_slot' => clienttranslate('feet'),
        'asset_name' => clienttranslate('armor_scale_feet'),
        'title' => clienttranslate('Armor: scale feet'),
    ],
    'armor_assassin_head' => [
        'source_name' => clienttranslate('Card_68.png'),
        'card_group' => clienttranslate('armor'),
        'armor_set' => clienttranslate('assassin'),
        'armor_slot' => clienttranslate('head'),
        'asset_name' => clienttranslate('armor_assassin_head'),
        'title' => clienttranslate('Armor: assassin head'),
    ],
    'armor_assassin_chest' => [
        'source_name' => clienttranslate('Card_69.png'),
        'card_group' => clienttranslate('armor'),
        'armor_set' => clienttranslate('assassin'),
        'armor_slot' => clienttranslate('chest'),
        'asset_name' => clienttranslate('armor_assassin_chest'),
        'title' => clienttranslate('Armor: assassin chest'),
    ],
    'armor_assassin_hands' => [
        'source_name' => clienttranslate('Card_70.png'),
        'card_group' => clienttranslate('armor'),
        'armor_set' => clienttranslate('assassin'),
        'armor_slot' => clienttranslate('hands'),
        'asset_name' => clienttranslate('armor_assassin_hands'),
        'title' => clienttranslate('Armor: assassin hands'),
    ],
    'armor_assassin_feet' => [
        'source_name' => clienttranslate('Card_71.png'),
        'card_group' => clienttranslate('armor'),
        'armor_set' => clienttranslate('assassin'),
        'armor_slot' => clienttranslate('feet'),
        'asset_name' => clienttranslate('armor_assassin_feet'),
        'title' => clienttranslate('Armor: assassin feet'),
    ],
    'xp' => [
        'source_name' => clienttranslate('Card_72.png'),
        'asset_name' => clienttranslate('xp'),
        'title' => clienttranslate('Experience'),
    ],
    'grit' => [
        'source_name' => clienttranslate('Card_73.png'),
        'asset_name' => clienttranslate('grit'),
        'title' => clienttranslate('Grit'),
    ],
];
