class StaticDataCards {
  static cardMetadata: any = {
    attr_str_1: { title: 'Strength +1', sortWeight: 1 },
    attr_dex_1: { title: 'Dexterity +1', sortWeight: 3 },
    attr_con_1: { title: 'Constitution +1', sortWeight: 5 },
    attr_wis_1: { title: 'Wisdom +1', sortWeight: 7 },
    attr_int_1: { title: 'Intelligence +1', sortWeight: 9 },
    attr_cha_1: { title: 'Charisma +1', sortWeight: 11 },
    attr_str_2: { title: 'Strength +2', sortWeight: 2 },
    attr_dex_2: { title: 'Dexterity +2', sortWeight: 4 },
    attr_con_2: { title: 'Constitution +2', sortWeight: 6 },
    attr_wis_2: { title: 'Wisdom +2', sortWeight: 8 },
    attr_int_2: { title: 'Intelligence +2', sortWeight: 10 },
    attr_cha_2: { title: 'Charisma +2', sortWeight: 12 },
    item_1: { title: 'Silver Sword', sortWeight: 200 },
    item_2: { title: 'Compact Crossbow', sortWeight: 201 },
    item_3: { title: 'Poison Antidote', sortWeight: 202 },
    item_4: { title: 'Binding Rope', sortWeight: 203 },
    item_5: { title: 'Phantom Lantern', sortWeight: 204 },
    item_6: { title: 'Loaded Dice', sortWeight: 205 },
    item_7: { title: 'Handy Cannon', sortWeight: 206 },
    item_8: { title: 'Reflective Shield', sortWeight: 207 },
    item_9: { title: 'Awakened Artifact', sortWeight: 208 },
    item_10: { title: 'Wooden Stake', sortWeight: 209 },
    item_11: { title: 'Glacial Spear', sortWeight: 210 },
    item_12: { title: 'Sea Trident', sortWeight: 211 },
    item_13: { title: 'Iron Horseshoes', sortWeight: 212 },
    item_14: { title: 'Holy Water', sortWeight: 213 },
    item_15: { title: 'Explosive Trap', sortWeight: 214 },
    item_16: { title: 'Woven Net', sortWeight: 215 },
    item_17: { title: 'Hypnotic Flute', sortWeight: 216 },
    item_18: { title: 'Crystal Goggles', sortWeight: 217 },
    item_19: { title: 'Burning Torch', sortWeight: 218 },
    item_20: { title: 'Music Box', sortWeight: 219 },
    item_21: { title: 'Cheese Wheel', sortWeight: 220 },
    armor_mage_head: { title: 'Armor: mage head', sortWeight: 100 },
    armor_mage_chest: { title: 'Armor: mage chest', sortWeight: 101 },
    armor_mage_hands: { title: 'Armor: mage hands', sortWeight: 102 },
    armor_mage_feet: { title: 'Armor: mage feet', sortWeight: 103 },
    armor_plate_head: { title: 'Armor: plate head', sortWeight: 110 },
    armor_plate_chest: { title: 'Armor: plate chest', sortWeight: 111 },
    armor_plate_hands: { title: 'Armor: plate hands', sortWeight: 112 },
    armor_plate_feet: { title: 'Armor: plate feet', sortWeight: 113 },
    armor_leather_head: { title: 'Armor: leather head', sortWeight: 120 },
    armor_leather_chest: { title: 'Armor: leather chest', sortWeight: 121 },
    armor_leather_hands: { title: 'Armor: leather hands', sortWeight: 122 },
    armor_leather_feet: { title: 'Armor: leather feet', sortWeight: 123 },
    armor_obsidian_head: { title: 'Armor: obsidian head', sortWeight: 130 },
    armor_obsidian_chest: { title: 'Armor: obsidian chest', sortWeight: 131 },
    armor_obsidian_hands: { title: 'Armor: obsidian hands', sortWeight: 132 },
    armor_obsidian_feet: { title: 'Armor: obsidian feet', sortWeight: 133 },
    armor_scale_head: { title: 'Armor: scale head', sortWeight: 140 },
    armor_scale_chest: { title: 'Armor: scale chest', sortWeight: 141 },
    armor_scale_hands: { title: 'Armor: scale hands', sortWeight: 142 },
    armor_scale_feet: { title: 'Armor: scale feet', sortWeight: 143 },
    armor_assassin_head: { title: 'Armor: assassin head', sortWeight: 150 },
    armor_assassin_chest: { title: 'Armor: assassin chest', sortWeight: 151 },
    armor_assassin_hands: { title: 'Armor: assassin hands', sortWeight: 152 },
    armor_assassin_feet: { title: 'Armor: assassin feet', sortWeight: 153 },
    xp: { title: 'Experience', sortWeight: 300 },
    grit: { title: 'Grit', sortWeight: 301 },
  };
}
